Development:

stripe_secret_key: 'sk_test_ty7qhPcFJd4uFGYvdCmZg58C008XPO1qcX'
stripe_publishable_key: 'pk_test_OwWjuHa0qjaV0l10959p9vzU00uw0J9wE8'

production:

stripe_secret_key: 'sk_test_ty7qhPcFJd4uFGYvdCmZg58C008XPO1qcX'
stripe_publishable_key: 'pk_test_OwWjuHa0qjaV0l10959p9vzU00uw0J9wE8'